### PR TITLE
top streams and games use system language

### PR DESCRIPTION
**Pull request by B0pol**
So that people get recommended video in their language -> better recommendations.

### CODE REVIEW

**Comment by micwoj92** [comment]
is there option to disable or is it hardcoded on?

**Comment by samfundev** [comment]
@micwoj92 From what I can see it is hardcoded on. Would you want there to be an option to disable it?

**Comment by micwoj92** [comment]
Yes, the option to choose is always better.

**Comment by Perflyst** [comment]
Hardcoding in the app looks fine to me, you can change your system language if you want an option...

**Comment by samfundev** [comment]
Personally I think we should ship this feature as most users will want it to behave this way. An issue can be opened up if there's demand for more options about controlling which languages should be shown.

**Pull request merged**
