### PR TITLE
Improve Spanish translation

### PR DESCRIPTION
**Pull request by sguinetti**
This pull request simplifies translation to improve the user interface.

### CODE REVIEW

**Comment by samfundev** [comment]
I really appreciate you improving the translations. Could you translate some other strings that are missing translations for Spanish? If not, I totally understand, just thought I'd ask.

**Comment by sguinetti** [comment]
I retranslated the line related to the disconnection. Although I don't understand what string needs updating.

**Comment by samfundev** [comment]
There's 6 strings that haven't been translated. The 6 strings are: stream_seek_dialog_title, stream_fullscreen, stream_viewers, stream_show_chat, stream_forward and stream_backward. They haven't been copied over to the strings.xml files as I'm not sure what the best practices are with that. I'd assume the best thing is to copy them over but remove the content so they don't get marked as being translated.You can see that they're not translated in Android Studio's translation editor but I wish there was some way for people to translate them without needing to install Android Studio.

If you or anyone else (maybe @Perflyst?) has any thoughts about any of what I said, let me know.

**Comment by samfundev** [comment]
There's 6 strings that haven't been translated. They are: stream_seek_dialog_title, stream_fullscreen, stream_viewers, stream_show_chat, stream_forward and stream_backward. They haven't been copied over to the strings.xml files as I'm not sure what the best practices are with that. I'd assume the best thing is to copy them over but remove the content so they don't get marked as being translated.

You can see that they're not translated in Android Studio's translation editor but I wish there was some way for people to translate them without needing to install Android Studio. So I had a thought about making an webapp that would allow you to translate any Android app by just pointing to it's GitHub repo. And if possible, I'd like to avoid requiring a server so that it wouldn't require any hosting and could be used by open source projects.

If you or anyone else (maybe @Perflyst?) has any thoughts about any of what I said, let me know.

**Comment by sguinetti** [comment]
@samfundev Have you ever heard of translatable="false"? Adding this code to each line would avoid translating the sentence. That's useful for info for debugging or trademarks. About adding a string file: The suggestion is that the Github web editor but it has many limitations.

**Comment by samfundev** [comment]
I have heard of that but I haven't reviewed the lines that were already in the app. I'll go through and mark off the ones that don't need to be translated. As for the web app I was talking about, I think I'm going to look into making it. Thanks for translating those new strings.

**Pull request merged**
