### PR TITLE
Dependency updates, code cleanup, and new adaptive icon

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update gradle wrapper to 6.4.1 using git bash

### 2nd commit
- Update appcompat 1.0.2 -> 1.1.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat))
- Update browser 1.1.0 -> 1.2.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/browser))
- Update recyclerview 1.0.0 -> 1.1.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/recyclerview))
- Update material 1.0.0 -> 1.1.0 ([changelog](https://github.com/material-components/material-components-android/releases))
- Update Glide 4.10.0 -> 4.11.0 ([changelog](https://github.com/bumptech/glide/releases))
- Update Guava 28.1-jre -> 29.0-jre ([changelog](https://github.com/google/guava/releases))
- Update Butterknife 10.2.0 -> 10.2.1 ([changelog](https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md))
- Update Exoplayer 2.11.1 -> 2.11.4 ([changelog](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md))

### 3rd commit
- Delete unused test activities

### 4th commit
- A little bit of code cleanup

### 5th commit
- Created an adaptive icon out of the ic_icon_foreground.xml (converted to png)

### CODE REVIEW

**Comment by samfun123** [comment]
Sorry I'm a bit confused about your last commit. I thought the app already has an adaptive icon using a vector drawable. I don't understand why you would want to make it a png instead of using a vector. Everything else looks pretty good though, thanks for the help.

**Comment by TacoTheDank** [comment]
The last time I checked the icon of the app on my phone, it wasn't adaptive... It seems to be now though, huh... ok I'll undo it.

**Comment by roshavagarga** [comment]
Small reminder - check if the dependencies are supported by F-Droid, sometimes they're a bit behind.

**Comment by TacoTheDank** [comment]
I believe F-Droid just pulls the dependencies from their respective sources, and I saw the commit that added gradle 6.4.1 support, so I think everything should be fine for this...

**Pull request merged**
